import { Destination } from '../types';

export const DESTINATIONS_DATA: Destination[] = [
    // Temples & Historical Sites
    {
        id: 'dest1',
        name: 'Borobudur Temple',
        category: 'Temples & Historical Sites',
        image: 'https://picsum.photos/seed/borobudur/600/400',
        bio: "Discover the awe-inspiring Borobudur, the world's largest Buddhist temple and a UNESCO World Heritage site. Built in the 9th century, this architectural marvel is adorned with over 2,500 relief panels and 504 Buddha statues. A pilgrimage for Buddhists, its intricate design represents the path to enlightenment.",
        distance: 42,
        rating: 4.9,
        info: {
            food: 'Many restaurants and stalls are available outside the main complex.',
            toilets: true,
            childFriendly: 'Yes, but be mindful of the many steep steps.',
            guideNeeded: 'Recommended to understand the history and reliefs.',
            insectRisk: false,
            openingHours: '7:30 AM - 5:00 PM',
        },
    },
    {
        id: 'dest2',
        name: 'Prambanan Temple',
        category: 'Temples & Historical Sites',
        image: 'https://picsum.photos/seed/prambanan/600/400',
        bio: 'Witness the grandeur of Prambanan, a magnificent 9th-century Hindu temple complex dedicated to the Trimurti: Brahma, Vishnu, and Shiva. Its towering, pointed architecture is a masterpiece of Hindu art and a testament to the region\'s rich history.',
        distance: 17,
        rating: 4.8,
        info: {
            food: true,
            toilets: true,
            childFriendly: true,
            guideNeeded: 'Helpful for understanding the Ramayana epic depicted on the reliefs.',
            insectRisk: false,
            openingHours: '6:30 AM - 5:00 PM',
        },
    },
     {
        id: 'dest3',
        name: 'Taman Sari (Water Castle)',
        category: 'Temples & Historical Sites',
        image: 'https://picsum.photos/seed/tamansari/600/400',
        bio: 'Explore the enchanting Taman Sari, a former royal garden and bathing complex for the Sultan of Yogyakarta. This site is a unique blend of European and Javanese architecture, featuring pools, underground tunnels, and meditation areas.',
        distance: 3,
        rating: 4.6,
        info: {
            food: 'Small cafes and street food available nearby.',
            toilets: true,
            childFriendly: true,
            guideNeeded: 'Can be useful to navigate the complex and find hidden spots.',
            insectRisk: false,
            openingHours: '9:00 AM - 3:00 PM',
        },
    },
    {
        id: 'dest9',
        name: 'Ratu Boko Palace',
        category: 'Temples & Historical Sites',
        image: 'https://picsum.photos/seed/ratuboko/600/400',
        bio: 'Perched on a plateau, the Ratu Boko archaeological site offers panoramic views and stunning sunsets. Believed to be the remains of a fortified palace, its grand gateways and pavilions hint at a glorious past.',
        distance: 18,
        rating: 4.7,
        info: {
            food: 'A restaurant with a view is available on site.',
            toilets: true,
            childFriendly: true,
            guideNeeded: 'Recommended for historical context.',
            insectRisk: false,
            openingHours: '7:00 AM - 5:00 PM',
        },
    },
    {
        id: 'dest10',
        name: 'Sewu Temple',
        category: 'Temples & Historical Sites',
        image: 'https://picsum.photos/seed/sewu/600/400',
        bio: 'Located within the Prambanan complex, Sewu Temple is the second largest Buddhist temple in Indonesia after Borobudur. Its name means "a thousand temples," reflecting its grand and expansive layout.',
        distance: 18,
        rating: 4.7,
        info: {
            food: 'Available at the main Prambanan complex.',
            toilets: true,
            childFriendly: true,
            guideNeeded: 'A combined guide for Prambanan is a good option.',
            insectRisk: false,
            openingHours: '6:30 AM - 5:00 PM',
        },
    },
    {
        id: 'dest11',
        name: 'Plaosan Temple',
        category: 'Temples & Historical Sites',
        image: 'https://picsum.photos/seed/plaosan/600/400',
        bio: 'Known for its unique blend of Hindu and Buddhist architectural elements, Plaosan Temple is a beautiful complex surrounded by rice paddies. It consists of two main temples, creating a serene and picturesque setting.',
        distance: 19,
        rating: 4.6,
        info: {
            food: 'Basic stalls nearby.',
            toilets: true,
            childFriendly: true,
            guideNeeded: false,
            insectRisk: false,
            openingHours: '8:00 AM - 5:00 PM',
        },
    },
    {
        id: 'dest12',
        name: 'Keraton Yogyakarta',
        category: 'Temples & Historical Sites',
        image: 'https://picsum.photos/seed/keraton/600/400',
        bio: 'The Keraton is the official residence of the Sultan of Yogyakarta and a living center of Javanese culture. Visitors can explore its courtyards, pavilions, and museums housing royal artifacts.',
        distance: 2,
        rating: 4.6,
        info: {
            food: 'Many options available just outside the complex.',
            toilets: true,
            childFriendly: true,
            guideNeeded: 'Highly recommended to understand the courtly culture.',
            insectRisk: false,
            openingHours: '8:30 AM - 2:00 PM (closes earlier on Fridays)',
        },
    },
    // Nature & Outdoors
    {
        id: 'dest4',
        name: 'Mount Merapi Jeep Tour',
        category: 'Nature & Outdoors',
        image: 'https://picsum.photos/seed/merapi/600/400',
        bio: 'Embark on an adventurous jeep tour on the slopes of Mount Merapi, one of Indonesia\'s most active volcanoes. The tour takes you through villages devastated by past eruptions, offering a raw, powerful look at the force of nature and stunning volcanic landscapes.',
        distance: 25,
        rating: 4.7,
        info: {
            food: 'Basic food stalls are at the jeep basecamps.',
            toilets: 'Available at basecamps.',
            childFriendly: 'Generally safe, but can be bumpy. Not for very young children.',
            guideNeeded: 'The jeep driver acts as your guide.',
            insectRisk: false,
            openingHours: 'Sunrise to late afternoon.',
        },
    },
    {
        id: 'dest5',
        name: 'Jomblang Cave',
        category: 'Nature & Outdoors',
        image: 'https://picsum.photos/seed/jomblang/600/400',
        bio: 'Descend into the mystical Jomblang Cave and witness the famous "heavenly light." A single beam of sunlight penetrates the darkness, illuminating the ancient forest below. This is a once-in-a-lifetime vertical caving experience.',
        distance: 50,
        rating: 4.9,
        info: {
            food: 'Lunch is usually included in the tour package.',
            toilets: 'Basic facilities available on site.',
            childFriendly: false,
            guideNeeded: true,
            insectRisk: 'Moderate. Insect repellent is a good idea.',
            openingHours: 'Booking required, descent is usually around 9:30 AM.',
        },
    },
    {
        id: 'dest6',
        name: 'Timang Beach',
        category: 'Nature & Outdoors',
        image: 'https://picsum.photos/seed/timang/600/400',
        bio: 'For the adrenaline junkies! Timang Beach is famous for its thrilling hand-pulled wooden gondola and suspension bridge that connect the mainland to a rocky outcrop over crashing waves. A truly unforgettable experience.',
        distance: 65,
        rating: 4.5,
        info: {
            food: 'Simple seafood restaurants are available.',
            toilets: true,
            childFriendly: false,
            guideNeeded: 'Local operators will manage the gondola/bridge.',
            insectRisk: false,
            openingHours: 'Daylight hours.',
        },
    },
    {
        id: 'dest13',
        name: 'Gunung Kidul Beaches',
        category: 'Nature & Outdoors',
        image: 'https://picsum.photos/seed/gunungkidul/600/400',
        bio: 'The Gunung Kidul region is a paradise of stunning beaches with white sand, clear turquoise water, and dramatic cliffs. Explore popular spots like Indrayanti, Drini, or find your own hidden gem along the coastline.',
        distance: 60,
        rating: 4.8,
        info: {
            food: 'Varies by beach, but most popular ones have many options.',
            toilets: true,
            childFriendly: true,
            guideNeeded: false,
            insectRisk: false,
            openingHours: '24/7, but best during the day.',
        },
    },
    {
        id: 'dest17',
        name: 'Indrayanti Beach',
        category: 'Nature & Outdoors',
        image: 'https://picsum.photos/seed/indrayanti/600/400',
        bio: 'One of the most popular beaches in Gunung Kidul, Indrayanti is known for its clean white sand, clear water, and well-managed facilities including gazebos and restaurants. A perfect spot for families and sunbathers.',
        distance: 62,
        rating: 4.7,
        info: {
            food: true,
            toilets: true,
            childFriendly: true,
            guideNeeded: false,
            insectRisk: false,
            openingHours: '24/7, restaurants open during the day.',
        },
    },
    {
        id: 'dest18',
        name: 'Kukup Beach',
        category: 'Nature & Outdoors',
        image: 'https://picsum.photos/seed/kukup/600/400',
        bio: 'Kukup Beach offers a wide expanse of sand and is famous for its coral island, "Pulau Jumino," which is connected by a bridge and offers great views. The beach is also a hub for local fishermen selling their fresh catch.',
        distance: 68,
        rating: 4.5,
        info: {
            food: 'Many fresh seafood stalls.',
            toilets: true,
            childFriendly: true,
            guideNeeded: false,
            insectRisk: false,
            openingHours: '24/7',
        },
    },
    {
        id: 'dest14',
        name: 'Tebing Breksi',
        category: 'Nature & Outdoors',
        image: 'https://picsum.photos/seed/breksi/600/400',
        bio: 'Once a limestone quarry, Tebing Breksi has been transformed into a unique tourist attraction with massive, intricately carved cliffs. Climb to the top for breathtaking views of the surrounding landscape and Prambanan temple.',
        distance: 20,
        rating: 4.5,
        info: {
            food: 'Many food and drink stalls are on site.',
            toilets: true,
            childFriendly: 'Yes, but supervision is needed near edges.',
            guideNeeded: false,
            insectRisk: false,
            openingHours: '6:00 AM - 8:00 PM',
        },
    },
    {
        id: 'dest15',
        name: 'Mangunan Pines Forest',
        category: 'Nature & Outdoors',
        image: 'https://picsum.photos/seed/mangunan/600/400',
        bio: 'Escape the city heat in the cool and fragrant Mangunan Pines Forest (Hutan Pinus Mangunan). It\'s a popular spot for photography and enjoying nature, with scenic viewing platforms offering misty morning views.',
        distance: 25,
        rating: 4.6,
        info: {
            food: true,
            toilets: true,
            childFriendly: true,
            guideNeeded: false,
            insectRisk: 'Moderate. Repellent is a good idea.',
            openingHours: '6:00 AM - 5:30 PM',
        },
    },
    // Culture & Art
    {
        id: 'dest7',
        name: 'Jalan Malioboro',
        category: 'Culture & Art',
        image: 'https://picsum.photos/seed/malioboro/600/400',
        bio: 'Immerse yourself in the heart of Yogyakarta at Jalan Malioboro. This vibrant street is the city\'s main shopping hub, bustling with local markets, street food vendors, horse-drawn carts, and a lively atmosphere that captures the spirit of Java.',
        distance: 1,
        rating: 4.7,
        info: {
            food: true,
            toilets: 'Available in malls and some restaurants.',
            childFriendly: true,
            guideNeeded: false,
            insectRisk: false,
            openingHours: 'Shops typically 10 AM - 9 PM, street is always active.',
        },
    },
    {
        id: 'dest8',
        name: 'Ramayana Ballet at Prambanan',
        category: 'Culture & Art',
        image: 'https://picsum.photos/seed/ramayana/600/400',
        bio: 'Experience the epic Hindu tale of Ramayana through a spectacular dance and theater performance. Set against the illuminated backdrop of Prambanan Temple, this show combines traditional Javanese dance, drama, and music into a mesmerizing spectacle.',
        distance: 18,
        rating: 4.8,
        info: {
            food: 'Restaurants on-site.',
            toilets: true,
            childFriendly: 'Yes, suitable for older children who can sit through a performance.',
            guideNeeded: false,
            insectRisk: 'Yes, it is an open-air theatre. Bring repellent.',
            openingHours: 'Evening shows, typically starting around 7:30 PM.',
        },
    },
    {
        id: 'dest16',
        name: 'Sonobudoyo Museum',
        category: 'Culture & Art',
        image: 'https://picsum.photos/seed/sonobudoyo/600/400',
        bio: 'Dive deep into Javanese history and culture at the Sonobudoyo Museum. It houses a diverse and impressive collection of historical artifacts, including gamelan instruments, weapons (keris), textiles, and puppets (wayang).',
        distance: 2,
        rating: 4.5,
        info: {
            food: 'Many options nearby.',
            toilets: true,
            childFriendly: true,
            guideNeeded: false,
            insectRisk: false,
            openingHours: '8:00 AM - 3:30 PM (Closed Mondays)',
        },
    },
];
