import { Room } from '../types';

export const ROOMS_DATA: Room[] = [
    {
        id: 'r1',
        vendorId: 'h1',
        name: 'Deluxe King Room',
        pricePerNight: 1200000,
        mainImage: 'https://picsum.photos/seed/r1_main/600/400',
        thumbnails: [
            'https://picsum.photos/seed/r1_thumb1/100/100',
            'https://picsum.photos/seed/r1_thumb2/100/100',
            'https://picsum.photos/seed/r1_thumb3/100/100',
        ],
        isAvailable: true,
        amenities: {
            wifi: true,
            tv: true,
            airConditioning: true,
            safe: true,
            miniBar: true,
            coffeeMaker: true,
            roomService: true,
            restaurantBar: true,
        },
        specialOffer: {
            enabled: true,
            discountPercentage: 25,
        },
    },
    {
        id: 'r2',
        vendorId: 'h1',
        name: 'Jungle View Suite',
        pricePerNight: 1850000,
        mainImage: 'https://picsum.photos/seed/r2_main/600/400',
        thumbnails: [
            'https://picsum.photos/seed/r2_thumb1/100/100',
            'https://picsum.photos/seed/r2_thumb2/100/100',
            'https://picsum.photos/seed/r2_thumb3/100/100',
        ],
        isAvailable: false,
        amenities: {
            wifi: true,
            tv: true,
            airConditioning: true,
            safe: true,
            miniBar: true,
            coffeeMaker: true,
            balcony: true,
            roomService: true,
            restaurantBar: true,
        },
    },
    {
        id: 'r3',
        vendorId: 'v10',
        name: 'Entire 3-Bedroom Villa',
        pricePerNight: 3500000,
        mainImage: 'https://picsum.photos/seed/r3_main/600/400',
        thumbnails: [
            'https://picsum.photos/seed/r3_thumb1/100/100',
            'https://picsum.photos/seed/r3_thumb2/100/100',
            'https://picsum.photos/seed/r3_thumb3/100/100',
        ],
        isAvailable: true,
        amenities: {
            wifi: true,
            tv: true,
            airConditioning: true,
            privatePool: true,
            balcony: true,
            restaurantBar: true,
            liveMusic: true,
        },
    },
    {
        id: 'r4', vendorId: 'h2', name: 'Ocean View King', pricePerNight: 2500000,
        mainImage: 'https://picsum.photos/seed/r4_main/600/400',
        thumbnails: ['https://picsum.photos/seed/r4_thumb1/100/100', 'https://picsum.photos/seed/r4_thumb2/100/100', 'https://picsum.photos/seed/r4_thumb3/100/100'],
        isAvailable: true,
        amenities: { wifi: true, tv: true, airConditioning: true, balcony: true, roomService: true },
    },
    {
        id: 'r5', vendorId: 'h2', name: 'Pool Access Suite', pricePerNight: 3200000,
        mainImage: 'https://picsum.photos/seed/r5_main/600/400',
        thumbnails: ['https://picsum.photos/seed/r5_thumb1/100/100', 'https://picsum.photos/seed/r5_thumb2/100/100', 'https://picsum.photos/seed/r5_thumb3/100/100'],
        isAvailable: true,
        amenities: { wifi: true, tv: true, airConditioning: true, miniBar: true, coffeeMaker: true, privatePool: true },
        specialOffer: { enabled: true, discountPercentage: 15 },
    },
    {
        id: 'r6', vendorId: 'h3', name: 'Family Room', pricePerNight: 1100000,
        mainImage: 'https://picsum.photos/seed/r6_main/600/400',
        thumbnails: ['https://picsum.photos/seed/r6_thumb1/100/100', 'https://picsum.photos/seed/r6_thumb2/100/100', 'https://picsum.photos/seed/r6_thumb3/100/100'],
        isAvailable: true,
        amenities: { wifi: true, tv: true, airConditioning: true },
    },
    {
        id: 'r7', vendorId: 'h3', name: 'Deluxe Queen', pricePerNight: 950000,
        mainImage: 'https://picsum.photos/seed/r7_main/600/400',
        thumbnails: ['https://picsum.photos/seed/r7_thumb1/100/100', 'https://picsum.photos/seed/r7_thumb2/100/100', 'https://picsum.photos/seed/r7_thumb3/100/100'],
        isAvailable: false,
        amenities: { wifi: true, tv: true, airConditioning: true, safe: true },
    }
];