

import { MenuItem, ShopItem } from '../types';

export const FOOD_CATEGORIES = {
    RICE_NOODLES: 'Rice and Noodle Dishes',
    SAVORY_SNACKS: 'Savory Snacks & Fritters',
    TRADITIONAL: 'Traditional & Regional Dishes',
    DRINKS_DESSERTS: 'Drinks & Desserts',
};

// FIX: Add mock data for SHOP_ITEMS to resolve import error.
export const SHOP_ITEMS: ShopItem[] = [
    { id: 'i1', name: 'Indomie Goreng (5 pack)', price: 15000, description: 'Instant noodles, popular Indonesian brand', image: 'https://picsum.photos/seed/indomie/200/200', vendorId: 'v3', isAvailable: true },
    { id: 'i2', name: 'Aqua 1.5L', price: 6000, description: 'Bottled mineral water', image: 'https://picsum.photos/seed/aqua/200/200', vendorId: 'v3', isAvailable: true },
    { id: 'i3', name: 'Kecap Manis Bango', price: 20000, description: 'Sweet soy sauce', image: 'https://picsum.photos/seed/kecap/200/200', vendorId: 'v3', isAvailable: true },
    { id: 'i4', name: 'Tolak Angin Cair (5 pack)', price: 18000, description: 'Herbal supplement for colds', image: 'https://picsum.photos/seed/tolakangin/200/200', vendorId: 'v3', isAvailable: true },
];

export const STREET_FOOD_ITEMS: MenuItem[] = [
    { id: 's1', name: 'Nasi Goreng Special', price: 25000, description: 'Rice, chicken, egg, sweet soy sauce, chili paste', longDescription: 'A quintessential Indonesian dish, Nasi Goreng is stir-fried rice with a sweet and savory kecap manis sauce, vegetables, and your choice of protein. Ours is served with a sunny-side-up egg.', image: 'https://ik.imagekit.io/7grri5v7d/nasi%20goreng.png?updatedAt=1759478879677', videoUrl: 'https://storage.googleapis.com/aistudio-ux-team-data/Racer/tiktok-food-1.mp4', vendorId: 'v1', category: FOOD_CATEGORIES.RICE_NOODLES, subcategory: 'Rice', isAvailable: true, chiliLevel: 2, cookingTime: 10, hasGarlic: true, tags: ['Rice', 'Spicy'] },
    { id: 's2', name: 'Bakso (Meatball Soup)', price: 20000, description: 'Beef meatballs, broth, noodles, celery', longDescription: 'A comforting and popular street food, Bakso consists of beef meatballs served in a hot broth with yellow noodles, rice vermicelli, and sprinkled with fried shallots and celery.', image: 'https://ik.imagekit.io/7grri5v7d/BAKSO%20SOUP.png?updatedAt=1759479466752', vendorId: 'v1', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Soup', isAvailable: true, chiliLevel: 1, cookingTime: 5, hasGarlic: true },
    { id: 's3', name: 'Sate Ayam (Chicken Satay)', price: 30000, description: 'Grilled chicken skewers, peanut sauce', longDescription: 'Tender pieces of chicken, marinated and skewered, then grilled over charcoal. Served with a rich and flavorful peanut sauce, lontong (rice cakes), and sliced shallots.', image: 'https://ik.imagekit.io/7grri5v7d/BAKSO%20SOUPS%20INDONISEA.png?updatedAt=1759479754735', videoUrl: 'https://storage.googleapis.com/aistudio-ux-team-data/Racer/tiktok-food-2.mp4', vendorId: 'v2', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Grilled', isAvailable: true, chiliLevel: 0, cookingTime: 15, hasGarlic: true },
    { id: 's4', name: 'Gado-Gado', price: 18000, description: 'Veggies, tofu, egg, peanut sauce', longDescription: 'A healthy and delicious Indonesian salad featuring a mix of blanched vegetables, boiled potatoes, hard-boiled eggs, tofu, and tempeh, all coated in a classic peanut sauce dressing.', image: 'https://ik.imagekit.io/7grri5v7d/BAKSO%20SOUPS%20INDONISEAS.png?updatedAt=1759480304846', videoUrl: 'https://storage.googleapis.com/aistudio-ux-team-data/Racer/tiktok-food-3.mp4', vendorId: 'v4', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Salad', isAvailable: true, chiliLevel: 1, cookingTime: 8, hasGarlic: true, tags: ['Salad'] },
    { id: 's5', name: 'Es Teh Manis (Sweet Iced Tea)', price: 5000, description: 'Refreshing sweet jasmine tea', longDescription: 'The perfect thirst-quencher for a hot day. Fragrant jasmine tea, brewed and sweetened, served over ice.', image: 'https://ik.imagekit.io/7grri5v7d/DRINKS%20INDONISEA.png?updatedAt=1759484189273', vendorId: 'v1', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Drinks', isAvailable: true, cookingTime: 2, hasGarlic: false },
    { id: 's6', name: 'Lontong (Rice Cake)', price: 5000, description: 'Compressed rice cake side', longDescription: 'A side dish made of compressed rice wrapped in a banana leaf. It\'s a common accompaniment to dishes like satay and gado-gado.', image: 'https://ik.imagekit.io/7grri5v7d/BAKSO%20SOUPS.png?updatedAt=1759479606170', vendorId: 'v2', category: FOOD_CATEGORIES.RICE_NOODLES, subcategory: 'Side', isAvailable: false, cookingTime: 1 },
    { id: 's11', name: 'Mie Goreng', price: 22000, description: 'Savory fried noodles with chicken & egg', longDescription: 'A savory fried noodle dish that is a staple of Indonesian street food, often mixed with chicken, egg, and vegetables.', image: 'https://picsum.photos/seed/miegoreng/200/200', videoUrl: 'https://storage.googleapis.com/aistudio-ux-team-data/Racer/tiktok-food-1.mp4', vendorId: 'v1', category: FOOD_CATEGORIES.RICE_NOODLES, subcategory: 'Noodle', isAvailable: true, chiliLevel: 1, cookingTime: 10, hasGarlic: true, tags: ['Noodle', 'Spicy'] },
    { id: 's12', name: 'Nasi Uduk', price: 18000, description: 'Fragrant coconut milk rice', longDescription: 'Fragrant rice cooked in coconut milk, a popular breakfast and lunch dish, often served with various side dishes like fried chicken, omelette, and tempeh.', image: 'https://picsum.photos/seed/nasiuduk/200/200', videoUrl: 'https://storage.googleapis.com/aistudio-ux-team-data/Racer/tiktok-food-2.mp4', vendorId: 'v4', category: FOOD_CATEGORIES.RICE_NOODLES, subcategory: 'Rice', isAvailable: true, chiliLevel: 0, cookingTime: 5, hasGarlic: true, tags: ['Rice'] },
    { id: 's13', name: 'Mie Ayam', price: 15000, description: 'Chicken noodle soup with wontons', longDescription: 'Chicken noodle soup, a Chinese-influenced dish that has become a national favorite. Served with diced chicken, wontons, and greens.', image: 'https://picsum.photos/seed/mieayam/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.RICE_NOODLES, subcategory: 'Noodle', isAvailable: true, chiliLevel: 0, cookingTime: 8, tags: ['Noodle'] },
    { id: 's14', name: 'Kwetiau Goreng', price: 24000, description: 'Stir-fried flat rice noodles', longDescription: 'A flat, stir-fried rice noodle dish, commonly cooked with beef, egg, and vegetables in a sweet and savory sauce.', image: 'https://picsum.photos/seed/kwetiau/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.RICE_NOODLES, subcategory: 'Noodle', isAvailable: true, chiliLevel: 1, cookingTime: 12, tags: ['Noodle'] },
    { id: 's15', name: 'Bubur Ayam', price: 12000, description: 'Savory chicken porridge', longDescription: 'Chicken porridge, a popular breakfast food. A warm and comforting rice congee topped with shredded chicken, scallions, fried shallots, and crackers.', image: 'https://picsum.photos/seed/buburayam/200/200', vendorId: 'v4', category: FOOD_CATEGORIES.RICE_NOODLES, subcategory: 'Porridge', isAvailable: true, chiliLevel: 0, cookingTime: 5, tags: ['Rice'] },
    { id: 's16', name: 'Tahu Isi', price: 3000, description: 'Fried tofu stuffed with vegetables', longDescription: 'A type of Gorengan (fritter). Crispy fried tofu filled with a savory mixture of bean sprouts, carrots, and sometimes minced meat.', image: 'https://picsum.photos/seed/tahuisi/200/200', vendorId: 'v4', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Gorengan', isAvailable: true, chiliLevel: 0, cookingTime: 7, tags: ['Crispy'] },
    { id: 's17', name: 'Tempe Goreng', price: 2000, description: 'Crispy fried tempeh fritter', longDescription: 'A simple yet beloved snack of deep-fried fermented soybean cake (tempeh), often lightly battered and seasoned.', image: 'https://picsum.photos/seed/tempegoreng/200/200', vendorId: 'v4', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Gorengan', isAvailable: true, chiliLevel: 0, cookingTime: 5, tags: ['Crispy'] },
    { id: 's18', name: 'Pisang Goreng', price: 3000, description: 'Sweet fried banana fritter', longDescription: 'A popular sweet snack or dessert. Sliced bananas are battered and deep-fried until golden and crispy.', image: 'https://picsum.photos/seed/pisanggoreng/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Gorengan', isAvailable: true, chiliLevel: 0, cookingTime: 6, tags: ['Crispy'] },
    { id: 's19', name: 'Cireng', price: 10000, description: 'Fried tapioca flour snack', longDescription: 'A chewy and savory snack made from tapioca flour, originating from West Java. Often served with a spicy dipping sauce.', image: 'https://picsum.photos/seed/cireng/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Gorengan', isAvailable: true, chiliLevel: 0, cookingTime: 8, tags: ['Crispy'] },
    { id: 's20', name: 'Martabak Manis', price: 40000, description: 'Sweet thick pancake with chocolate', longDescription: 'A sweet, thick pancake filled with various toppings like chocolate sprinkles, crushed peanuts, sesame seeds, and condensed milk.', image: 'https://picsum.photos/seed/martabakmanis/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Dessert', isAvailable: true, chiliLevel: 0, cookingTime: 15 },
    { id: 's21', name: 'Martabak Telor', price: 35000, description: 'Savory egg and meat pancake', longDescription: 'A savory and crispy folded pancake filled with a mixture of egg, minced meat (usually beef or chicken), and scallions.', image: 'https://picsum.photos/seed/martabaktelor/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Pancake', isAvailable: true, chiliLevel: 0, cookingTime: 15, tags: ['Crispy'] },
    { id: 's22', name: 'Siomay', price: 20000, description: 'Steamed fish dumplings with peanut sauce', longDescription: 'Steamed fish dumplings (similar to Chinese shumai) served with steamed potatoes, cabbage, and hard-boiled egg, all smothered in a savory peanut sauce.', image: 'https://picsum.photos/seed/siomay/200/200', videoUrl: 'https://storage.googleapis.com/aistudio-ux-team-data/Racer/tiktok-food-3.mp4', vendorId: 'v1', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Dumplings', isAvailable: true, chiliLevel: 1, cookingTime: 10 },
    { id: 's23', name: 'Batagor', price: 22000, description: 'Fried fish dumplings and tofu', longDescription: 'An acronym for Bakso Tahu Goreng. Fried fish dumplings and tofu served with a rich peanut sauce, sweet soy sauce, and a splash of lime.', image: 'https://ik.imagekit.io/7grri5v7d/INDONISEA%20FOODSSSS.png?updatedAt=1759486101825', vendorId: 'v4', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Fried', isAvailable: true, chiliLevel: 1, cookingTime: 12, tags: ['Crispy'] },
    { id: 's24', name: 'Kerak Telor', price: 25000, description: 'Spicy glutinous rice omelette', longDescription: 'A traditional Betawi (Jakarta native) spicy omelette, made from glutinous rice cooked with duck egg and served with fried shallots and shredded coconut.', image: 'https://ik.imagekit.io/7grri5v7d/INDONISEA%20FOODSSS.png?updatedAt=1759485908706', vendorId: 'v2', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Omelette', isAvailable: true, chiliLevel: 2, cookingTime: 10, hasGarlic: true },
    { id: 's25', name: 'Pempek', price: 28000, description: 'Savory fishcake from Palembang', longDescription: 'A savory fishcake delicacy from Palembang, South Sumatra, made of fish and tapioca. Served with a rich, dark, sweet and sour sauce called kuah cuko.', image: 'https://ik.imagekit.io/7grri5v7d/INDONISEA%20FOODSS.png?updatedAt=1759485543877', vendorId: 'v1', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Fishcake', isAvailable: true, chiliLevel: 1, cookingTime: 10, tags: ['Crispy'] },
    { id: 's26', name: 'Lumpia Semarang', price: 8000, description: 'Deep-fried spring roll', longDescription: 'A deep-fried or sometimes soft spring roll, typically filled with bamboo shoots, minced meat, and vegetables. A specialty of Semarang city.', image: 'https://ik.imagekit.io/7grri5v7d/INDONISEA%20FOODS.png?updatedAt=1759484963614', vendorId: 'v4', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Spring Roll', isAvailable: true, chiliLevel: 0, cookingTime: 8, tags: ['Crispy'] },
    { id: 's27', name: 'Ayam Bakar', price: 35000, description: 'Grilled spiced chicken with rice', longDescription: 'Charcoal-grilled chicken that has been marinated in a mixture of spices and sweet soy sauce. It is often served with steamed rice, sambal, and fresh vegetables.', image: 'https://picsum.photos/seed/ayambakar/200/200', videoUrl: 'https://storage.googleapis.com/aistudio-ux-team-data/Racer/tiktok-food-2.mp4', vendorId: 'v2', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Grilled', isAvailable: true, chiliLevel: 1, cookingTime: 20, hasGarlic: true, tags: ['Rice'] },
    { id: 's28', name: 'Rendang Sapi', price: 45000, description: 'Slow-cooked spicy beef', longDescription: 'A rich and tender slow-cooked meat dish, most commonly beef, that is rich with a complex blend of spices. Originating from West Sumatra.', image: 'https://picsum.photos/seed/rendang/200/200', videoUrl: 'https://storage.googleapis.com/aistudio-ux-team-data/Racer/tiktok-food-1.mp4', vendorId: 'v1', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Beef', isAvailable: true, chiliLevel: 3, cookingTime: 25, hasGarlic: true, tags: ['Spicy', 'Rice'] },
    { id: 's29', name: 'Soto Ayam', price: 18000, description: 'Traditional chicken soup', longDescription: 'A traditional Indonesian soup mainly composed of broth, chicken, and vegetables. Many regions have their own variations, but it is typically served with rice.', image: 'https://picsum.photos/seed/sotoayam/200/200', vendorId: 'v4', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Soup', isAvailable: true, chiliLevel: 0, cookingTime: 8, tags: ['Rice'] },
    { id: 's30', name: 'Nasi Padang (Rames)', price: 30000, description: 'Rice with various Padang dishes', longDescription: 'A miniature version of the Padang feast on one plate. Steamed rice served with a collection of pre-cooked dishes, such as rendang, curried vegetables, and sambal.', image: 'https://picsum.photos/seed/nasipadang/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Rice', isAvailable: true, chiliLevel: 2, cookingTime: 5, tags: ['Rice', 'Spicy'] },
    { id: 's31', name: 'Es Cendol', price: 12000, description: 'Iced dessert with rice flour jelly', longDescription: 'A refreshing iced dessert made with green rice flour jellies, coconut milk, and palm sugar syrup. Sometimes served with jackfruit.', image: 'https://picsum.photos/seed/escendol/200/200', videoUrl: 'https://storage.googleapis.com/aistudio-ux-team-data/Racer/tiktok-food-3.mp4', vendorId: 'v4', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Dessert', isAvailable: true, cookingTime: 3 },
    { id: 's32', name: 'Es Teler', price: 15000, description: 'Iced dessert with avocado & jackfruit', longDescription: 'A popular Indonesian fruit cocktail. It is a dessert with avocado, coconut meat, jackfruit, and other fruits, served with coconut milk, condensed milk, and syrup.', image: 'https://picsum.photos/seed/esteler/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Dessert', isAvailable: true, cookingTime: 4 },
    { id: 's33', name: 'Jus Alpukat', price: 15000, description: 'Thick avocado juice with chocolate', longDescription: 'A popular and rich avocado juice, which is more like a smoothie. Often served with a swirl of chocolate syrup inside the glass.', image: 'https://picsum.photos/seed/jusalpukat/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Drinks', isAvailable: true, cookingTime: 4 },
    { id: 's34', name: 'Wedang Ronde', price: 10000, description: 'Hot ginger drink with rice balls', longDescription: 'A traditional Javanese hot ginger drink served with sweet glutinous rice balls filled with crushed peanuts. Very comforting on a cool evening.', image: 'https://picsum.photos/seed/wedangronde/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Hot Drink', isAvailable: true, cookingTime: 5 },
    { id: 's35', name: 'Sekoteng', price: 10000, description: 'Warm, ginger-based drink', longDescription: 'A warm, ginger-based drink with various fillings like peanuts, pearl sago, and pieces of bread. A traditional night-time beverage.', image: 'https://picsum.photos/seed/sekoteng/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Hot Drink', isAvailable: true, cookingTime: 5 },
    { id: 's36', name: 'Es Doger', price: 13000, description: 'Pink coconut milk ice dessert', longDescription: 'An iced dessert from West Java made with pink-colored shaved ice, coconut milk, and various toppings like fermented cassava, black glutinous rice, and jackfruit.', image: 'https://picsum.photos/seed/esdoger/200/200', vendorId: 'v4', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Dessert', isAvailable: true, cookingTime: 4 },
    { id: 's37', name: 'Es Campur', price: 15000, description: 'Mixed ice dessert with various fruits', longDescription: 'A colorful and popular "mixed ice" dessert. It contains a wide variety of fruits, jellies, tapioca pearls, and grass jelly, served with shaved ice, syrup, and condensed milk.', image: 'https://picsum.photos/seed/escampur/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Dessert', isAvailable: true, cookingTime: 4 },
    // NEW MOCK ITEMS TO FILL SCROLL
    { id: 's38', name: 'Sop Buntut', price: 45000, description: 'Rich oxtail soup', longDescription: 'A clear beef soup made with tender oxtail, carrots, and potatoes. Served with steamed rice, sambal, and lime.', image: 'https://picsum.photos/seed/sopbuntut/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Soup', isAvailable: true, chiliLevel: 0, cookingTime: 15, tags: ['Rice'] },
    { id: 's39', name: 'Gudeg Jogja', price: 25000, description: 'Sweet jackfruit stew', longDescription: 'A traditional Javanese dish from Yogyakarta made from young unripe jackfruit boiled for several hours with palm sugar and coconut milk.', image: 'https://picsum.photos/seed/gudeg/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Rice', isAvailable: true, chiliLevel: 0, cookingTime: 10, tags: ['Rice'] },
    { id: 's40', name: 'Rawon', price: 30000, description: 'Black beef soup', longDescription: 'A strong rich tasting traditional Indonesian beef soup. Uses black nuts (kluwek) as the main seasoning, which gives a dark color and nutty flavor.', image: 'https://picsum.photos/seed/rawon/200/200', vendorId: 'v4', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Soup', isAvailable: true, chiliLevel: 1, cookingTime: 12, tags: ['Rice'] },
    { id: 's41', name: 'Es Kelapa Muda', price: 10000, description: 'Young coconut ice', longDescription: 'Fresh young coconut water served with its flesh and ice. Very refreshing!', image: 'https://picsum.photos/seed/eskelapa/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Drinks', isAvailable: true, cookingTime: 2 },
    { id: 's42', name: 'Es Jeruk', price: 8000, description: 'Fresh squeezed orange ice', longDescription: 'Freshly squeezed local oranges served with ice and a little sugar syrup.', image: 'https://picsum.photos/seed/esjeruk/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Drinks', isAvailable: true, cookingTime: 3 },
    { id: 's43', name: 'Kopi Tubruk', price: 6000, description: 'Traditional black coffee', longDescription: 'Indonesian style unfiltered black coffee. Strong and bold.', image: 'https://picsum.photos/seed/kopitubruk/200/200', vendorId: 'v4', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Coffee', isAvailable: true, cookingTime: 3 },
    { id: 's44', name: 'Klepon', price: 5000, description: 'Sweet rice balls with palm sugar', longDescription: 'Boiled rice cake stuffed with liquid palm sugar and rolled in grated coconut.', image: 'https://picsum.photos/seed/klepon/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Dessert', isAvailable: true, cookingTime: 0 },
    { id: 's45', name: 'Dadar Gulung', price: 5000, description: 'Green coconut pancake', longDescription: 'A traditional snack of sweet coconut pancake filled with grated coconut and palm sugar.', image: 'https://picsum.photos/seed/dadargulung/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Dessert', isAvailable: true, cookingTime: 0 },
    { id: 's46', name: 'Risoles', price: 4000, description: 'Savory crepe roll', longDescription: 'A crepe roll filled with vegetables and meat, breaded and deep fried.', image: 'https://picsum.photos/seed/risoles/200/200', vendorId: 'v4', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Gorengan', isAvailable: true, chiliLevel: 0, cookingTime: 0, tags: ['Crispy'] },
    { id: 's47', name: 'Bakwan Jagung', price: 3000, description: 'Corn fritter', longDescription: 'Crispy corn fritters seasoned with garlic and scallions.', image: 'https://picsum.photos/seed/bakwanjagung/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Gorengan', isAvailable: true, chiliLevel: 0, cookingTime: 5, tags: ['Crispy'] },
    { id: 's48', name: 'Sate Lilit', price: 35000, description: 'Balinese minced meat satay', longDescription: 'Minced meat (pork, fish, or chicken) mixed with grated coconut, coconut milk, lemon juice, shallots, and pepper.', image: 'https://picsum.photos/seed/satelilit/200/200', vendorId: 'v5', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Satay', isAvailable: true, chiliLevel: 2, cookingTime: 15 },
    { id: 's49', name: 'Lawar', price: 20000, description: 'Balinese vegetable mix', longDescription: 'A mix of vegetables, coconut, and minced meat mixed with rich herbs and spices.', image: 'https://picsum.photos/seed/lawar/200/200', vendorId: 'v5', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Side', isAvailable: true, chiliLevel: 3, cookingTime: 10, tags: ['Salad', 'Spicy'] },
    { id: 's50', name: 'Bebek Betutu', price: 85000, description: 'Slow roasted duck', longDescription: 'Balinese dish of steamed or roasted duck in rich bumbu betutu spices.', image: 'https://picsum.photos/seed/bebekbetutu/200/200', vendorId: 'v5', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Duck', isAvailable: true, chiliLevel: 3, cookingTime: 30, tags: ['Spicy'] },
    { id: 's51', name: 'Smoothie Bowl', price: 55000, description: 'Mixed berry smoothie bowl', longDescription: 'Frozen berries, banana, and coconut milk topped with granola and fresh fruit.', image: 'https://picsum.photos/seed/smoothiebowl/200/200', vendorId: 'v6', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Brunch', isAvailable: true, cookingTime: 5, tags: ['Salad'] },
    { id: 's52', name: 'Vegan Burger', price: 75000, description: 'Plant-based patty burger', longDescription: 'House-made plant patty with lettuce, tomato, and vegan mayo on a whole wheat bun.', image: 'https://picsum.photos/seed/veganburger/200/200', vendorId: 'v6', category: FOOD_CATEGORIES.RICE_NOODLES, subcategory: 'Western', isAvailable: true, cookingTime: 12 },
    { id: 's53', name: 'Matcha Latte', price: 40000, description: 'Green tea latte', longDescription: 'High quality matcha powder whisked with steamed milk.', image: 'https://picsum.photos/seed/matchalatte/200/200', vendorId: 'v6', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Hot Drink', isAvailable: true, cookingTime: 4 },
    { id: 's54', name: 'Soto Betawi', price: 35000, description: 'Beef soup with coconut milk', longDescription: 'Rich and creamy beef soup from Jakarta with coconut milk and spices.', image: 'https://picsum.photos/seed/sotobetawi/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Soup', isAvailable: true, chiliLevel: 0, cookingTime: 10, tags: ['Rice'] },
    { id: 's55', name: 'Kerupuk', price: 2000, description: 'Crackers', longDescription: 'Assorted Indonesian crackers, perfect side for any meal.', image: 'https://picsum.photos/seed/kerupuk/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Side', isAvailable: true, cookingTime: 0, tags: ['Crispy'] },
    { id: 's56', name: 'Teh Botol', price: 5000, description: 'Sweet jasmine tea bottle', longDescription: 'Iconic Indonesian bottled jasmine tea.', image: 'https://picsum.photos/seed/tehbotol/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Drinks', isAvailable: true, cookingTime: 0 },
    { id: 's57', name: 'Kopi Susu Gula Aren', price: 18000, description: 'Iced coffee with palm sugar', longDescription: 'Trendy iced coffee with milk and liquid palm sugar.', image: 'https://picsum.photos/seed/kopisusu/200/200', vendorId: 'v4', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Coffee', isAvailable: true, cookingTime: 3 },
    { id: 's58', name: 'Singkong Keju', price: 12000, description: 'Fried cassava with cheese', longDescription: 'Fried cassava topped with grated cheese and condensed milk.', image: 'https://picsum.photos/seed/singkongkeju/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Fried', isAvailable: true, cookingTime: 8 },
    { id: 's59', name: 'Seblak', price: 15000, description: 'Spicy wet cracker soup', longDescription: 'Savory and spicy dish made of wet crackers cooked with egg and vegetables.', image: 'https://picsum.photos/seed/seblak/200/200', vendorId: 'v4', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Spicy', isAvailable: true, chiliLevel: 4, cookingTime: 8, tags: ['Spicy'] },
    { id: 's60', name: 'Cilok', price: 5000, description: 'Tapioca balls with peanut sauce', longDescription: 'Chewy tapioca balls steamed and served with spicy peanut sauce.', image: 'https://picsum.photos/seed/cilok/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Gorengan', isAvailable: true, chiliLevel: 1, cookingTime: 5, tags: ['Spicy'] },
    { id: 's61', name: 'Es Cincau', price: 8000, description: 'Grass jelly ice', longDescription: 'Grass jelly served with coconut milk and syrup.', image: 'https://picsum.photos/seed/escincau/200/200', vendorId: 'v2', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Drinks', isAvailable: true, cookingTime: 2 },
    // New Items for Filter Demo
    { id: 's62', name: 'Ayam Geprek', price: 22000, description: 'Smashed spicy fried chicken', longDescription: 'Crispy battered fried chicken smashed with spicy sambal.', image: 'https://picsum.photos/seed/ayamgeprek/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Chicken', isAvailable: true, chiliLevel: 4, cookingTime: 15, hasGarlic: true, tags: ['Spicy', 'Crispy', 'Rice'] },
    { id: 's63', name: 'Kerupuk Putih (Blek)', price: 2000, description: 'Classic white cracker', longDescription: 'Crunchy white cracker in the traditional tin.', image: 'https://picsum.photos/seed/kerupukputih/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Side', isAvailable: true, cookingTime: 0, tags: ['Crispy'] },
    { id: 's64', name: 'Salad Buah Segar', price: 18000, description: 'Fresh fruit salad', longDescription: 'Mix of tropical fruits with cheese and mayo dressing.', image: 'https://picsum.photos/seed/saladbuah/200/200', vendorId: 'v1', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Dessert', isAvailable: true, cookingTime: 5, tags: ['Salad'] },
];

export const BALI_STREET_FOOD_ITEMS: MenuItem[] = [
    { id: 's7', name: 'Babi Guling (Suckling Pig)', price: 50000, description: 'Roast pork, rice, lawar, spicy sambal', longDescription: 'A Balinese culinary icon, Babi Guling is a whole pig stuffed with a rich blend of Balinese spices, then roasted to perfection. Served with steamed rice, lawar, and crispy pork skin.', image: 'https://picsum.photos/seed/babiguling/200/200', videoUrl: 'https://storage.googleapis.com/aistudio-ux-team-data/Racer/tiktok-food-2.mp4', vendorId: 'v5', category: FOOD_CATEGORIES.TRADITIONAL, subcategory: 'Pork', isAvailable: true, chiliLevel: 3, cookingTime: 20, hasGarlic: true, tags: ['Rice', 'Spicy', 'Crispy'] },
    { id: 's8', name: 'Nasi Campur Bali', price: 35000, description: 'Mixed rice with various small dishes', longDescription: 'A plate of steamed rice served with a variety of small portions of other dishes, which may include meat, vegetables, peanuts, eggs, and fried-shrimp krupuk.', image: 'https://picsum.photos/seed/nasicampurbali/200/200', vendorId: 'v5', category: FOOD_CATEGORIES.RICE_NOODLES, subcategory: 'Rice', isAvailable: true, chiliLevel: 2, cookingTime: 12, tags: ['Rice'] },
    { id: 's9', name: 'Iced Latte', price: 35000, description: 'Espresso with chilled milk', longDescription: 'A perfect coffee for a warm day, made with a shot of rich espresso and cold, fresh milk, served over ice.', image: 'https://picsum.photos/seed/latte/200/200', vendorId: 'v6', category: FOOD_CATEGORIES.DRINKS_DESSERTS, subcategory: 'Coffee', isAvailable: true, cookingTime: 3 },
    { id: 's10', name: 'Avocado Toast', price: 65000, description: 'Sourdough with avocado and feta', longDescription: 'Toasted artisanal sourdough bread topped with smashed avocado, crumbled feta cheese, and a sprinkle of chili flakes.', image: 'https://picsum.photos/seed/avotoast/200/200', videoUrl: 'https://storage.googleapis.com/aistudio-ux-team-data/Racer/tiktok-food-1.mp4', vendorId: 'v6', category: FOOD_CATEGORIES.SAVORY_SNACKS, subcategory: 'Brunch', isAvailable: true, chiliLevel: 0, cookingTime: 7, hasGarlic: false, tags: ['Crispy'] },
];

export const BALI_SHOP_ITEMS: ShopItem[] = [
    { id: 'i5', name: 'Surfboard Rental (Day)', price: 150000, description: 'Beginner to intermediate boards', image: 'https://picsum.photos/seed/surfboard/200/200', vendorId: 'v7', isAvailable: true },
    { id: 'i6', name: 'Surf Wax', price: 25000, description: 'Tropical water surf wax', image: 'https://picsum.photos/seed/surfwax/200/200', vendorId: 'v7', isAvailable: true },
    { id: 'b7i1', name: 'Yoga Class (Drop-in)', price: 150000, description: '90-minute vinyasa flow class', image: 'https://picsum.photos/seed/yogaclass/200/200', vendorId: 'b7', isAvailable: true },
    { id: 'b7i2', name: '5 Class Pass', price: 650000, description: 'Valid for one month.', image: 'https://picsum.photos/seed/yogapass/200/200', vendorId: 'b7', isAvailable: true },
    { id: 'b8i1', name: 'Silver Ring Making Class', price: 400000, description: '3-hour class, includes 5g silver', image: 'https://picsum.photos/seed/silverclass/200/200', vendorId: 'b8', isAvailable: true },
];
